stages:
  - build

build:
  stage: build
  image: ubuntu:latest

  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - build/
      - /var/cache/apt/archives/ # Faster with caching the dependency downloads

  before_script:
    - apt-get update
    - apt-get install -y cmake make git g++ libcppunit-dev libsqlite3-dev qtbase5-dev libboost-system-dev libboost-thread-dev

  script:
    - make
