stages:
  - build

build:
  stage: build
  image: ubuntu:latest

  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - build/
      - /var/cache/apt/archives/ # Faster with caching the dependency downloads

  before_script:
    - dpkg -s libboost-system-dev
    - export DEBIAN_FRONTEND=noninteractive
    - apt update && apt install -y cmake make git g++ libcppunit-dev libsqlite3-dev qtbase5-dev libboost-system-dev

  script:
    - make

  artifacts:
    paths:
      - build/
    expire_in: 1 week

  after_script:
    - rm -rf /var/lib/apt/lists/*
