@startuml (id=EffectClass)

skinparam linetype ortho

!include ./Bonus/BonusClass.plantuml!0
!include ./Bonus/MiniTetrominoesClass.plantuml!0
!include ./Bonus/SlowDownClass.plantuml!0
!include ./Bonus/TimedBonus.plantuml!0

!include ./Penalty/Blackout.plantuml!0
!include ./Penalty/InputLock.plantuml!0
!include ./Penalty/Penalty.plantuml!0
!include ./Penalty/ReverseControls.plantuml!0
!include ./Penalty/SpeedUp.plantuml!0
!include ./Penalty/TimedPenalty.plantuml!0

!include EffectSelector.plantuml!0
!include AbstractTimedEffect.plantuml!0
!include PlacementTimedEffect.plantuml!0
!include TickTimedEffect.plantuml!0

AbstractTimedEffect <|-- PlacementTimedEffect


AbstractTimedEffect <|-- TickTimedEffect


AbstractTimedEffect <|-- TimedBonus


AbstractTimedEffect <|-- TimedPenalty


PlacementTimedEffect <|-- InputLock


PlacementTimedEffect <|-- ReverseControls


TetrisObserver <|-- PlayerState


TickTimedEffect <|-- Blackout


TickTimedEffect <|-- SlowDown


TickTimedEffect <|-- SpeedUp


TimedBonus <|-- SlowDown


TimedPenalty <|-- Blackout


TimedPenalty <|-- InputLock


TimedPenalty <|-- ReverseControls


TimedPenalty <|-- SpeedUp


TimedBonus *-- BonusType


TimedPenalty *-- PenaltyType


@enduml