@startuml (id = PlacementTimedEffect)

class PlacementTimedEffect {
	#PlacementTimedEffect(size_t placementsNum)
	#PlacementTimedEffect(const PlacementTimedEffect &)
	#PlacementTimedEffect(PlacementTimedEffect& &)
	+~PlacementTimedEffect()
	#operator=(const PlacementTimedEffect &) : PlacementTimedEffect&
	#operator=(PlacementTimedEffect& &) : PlacementTimedEffect&
	+isFinished() : bool {query}
	+operator==(const PlacementTimedEffect& other) : bool {query}
	+getElapsedTime() : double {query}
	-numPlacements_ : size_t
	-remainingPlacements_ : size_t
	+operator<<(std::ostream& os, const PlacementTimedEffect& placementTimedEffect) : std : : ostream&
	+tetrominoPlaced() : void
}

@enduml