@startuml (id = TickTimedEffect)

class TickTimedEffect {
	#TickTimedEffect(size_t ticksNum)
	#TickTimedEffect(const TickTimedEffect &)
	#TickTimedEffect(TickTimedEffect& &)
	+~TickTimedEffect()
	#operator=(const TickTimedEffect &) : TickTimedEffect&
	#operator=(TickTimedEffect& &) : TickTimedEffect&
	+isFinished() : bool {query}
	+operator==(const TickTimedEffect& other) : bool {query}
	+getElapsedTime() : double {query}
	-numTicks_ : size_t
	-remainingTicks_ : size_t
	+operator<<(std::ostream& os, const TickTimedEffect& tickTimedEffect) : std : : ostream&
	+tick() : void
}


@enduml