@startuml (id=TimedPenalty)


class TimedPenalty {
    - PenaltyType penaltyType_
    # TimedPenalty(PenaltyType penaltyType)
    # TimedPenalty(const TimedPenalty &) : void
    # TimedPenalty(TimedPenalty &&) : void
    # TimedPenalty &operator=(const TimedPenalty &) : void
    # TimedPenalty &operator=(TimedPenalty &&) : void
    + ~TimedPenalty()
    + {static} makePenalty(PenaltyType bonusType) : TimedPenaltyPtr
    + getPenaltyType() const : PenaltyType
} 


@enduml
