@startuml (id = GridCell )

class GridCell {
    - colorId_ : optional<unsigned>

    + isEmpty() : const bool
    + getColorId() : const unsigned
    + setColorId( colorId : unsigned ) : void
    + setEmpty() : void 

    + serialize() : const nlohmann::json
    + deserialize( &j : const nlohmann::json) : void 
    
}
@enduml