@startuml (id = GridCell )

class GridCell {
	-colorId_ : std::optional<unsigned>

	+GridCell()
	+GridCell(const GridCell &)
	+GridCell(GridCell& &)
	+~GridCell()

	+operator=(const GridCell &) : GridCell&
	+operator=(GridCell& &) : GridCell&

	+isEmpty() : bool {query}
	+getColorId() : std::optional<unsigned> {query}
	
	+setColorId(unsigned colorId) : void
	+setEmpty() : void

	+serialize() : nlohmann::json {query}
	+deserialize(const nlohmann::json& j) : void
}
@enduml