/' authors Ernest Jonas Rafaou '/
@startuml (id = TetrisObserver)
abstract class TetrisObserver {
	+TetrisObserver()
	+TetrisObserver(const TetrisObserver &)
	+TetrisObserver(TetrisObserver& &)
	+~TetrisObserver()

	+operator=(const TetrisObserver &) : TetrisObserver&
	+operator=(TetrisObserver& &) : TetrisObserver&
	
	+{abstract} notifyActiveTetrominoPlaced() : void
	+{abstract} notifyLost() : void
}
@enduml