/' authors Ernest Jonas Rafaou '/
@startuml (id=TetrominoQueue)
class TetrominoQueue {
	-{static} NUM_SERIALIZED_TETROMINOES : static constexpr size_t
	-queue_ : std::deque<shared_ptr<ATetromino>>

	+TetrominoQueue()
	+TetrominoQueue(const TetrominoQueue &)
	+TetrominoQueue(TetrominoQueue& &)
	+~TetrominoQueue()

	+operator=(const TetrominoQueue &) : TetrominoQueue&
	+operator=(TetrominoQueue& &) : TetrominoQueue&

	+front() : shared_ptr<ATetromino>&
	+size() : size_t {query}
	+fetchNext() : shared_ptr<ATetromino>
	+insertNextTetromino(shared_ptr<ATetromino> pTetromino) : void
	+refill() : void

	+serialize() : nlohmann::json {query}
}
@enduml