/' authors Ernest Jonas Rafaou '/
@startuml (id=Vec2)
class Vec2 {
    - x_ : int
    - y_ : int
   
    + Vec2(x : int = 0, y : int = 0)

    + Vec2(const Vec2 &) = default
    + Vec2(Vec2 &&) = default
    + operator=(const Vec2 &) : Vec2& = default
    + operator=(Vec2 &&) : Vec2& = default
    + ~Vec2() = default

    + getX() : int const noexcept
    + getY() : int const noexcept

    + setX(x : int) : void
    + setY(y : int) : void
    + moveX(x : int) : void
    + moveY(y : int) : void

    + operator==(other : const Vec2&) : bool const
    + operator!=(other : const Vec2&) : bool const
    + operator+(other : const Vec2&) : Vec2 const
    + operator+=(other : const Vec2&) : Vec2&
    + operator-(other : const Vec2&) : Vec2 const
    + operator-=(other : const Vec2&) : Vec2&
    + operator-() : Vec2 const

    + rotateAround(rotationCenter : const Vec2&, rotateClockwise : bool) : const Vec2&
    
    + serialize() : nlohmann::json const
    + deserialize(j : const nlohmann::json&) : void
}
@enduml