@startuml NetworkManagerClass
skinparam linetype ortho




/' Objects '/

class NetworkManager {
	' -context_ : boost::asio::io_context&
	-socket_ : boost::asio::ip::tcp::socket
	-retryTimer_ : boost::asio::steady_timer
	-readBuf_ : std::string
	-isConnected_ : bool

	-serverIp_ : std::string
	-serverPort_ : uint16_t
	
	-function<void(const std::string_view)
	-connect() : bool
	-receive() : void
	-write() : void
	-retry() : void

	+NetworkManager(boost::asio::io_context& context, std::function<void ( const std::string_view )> packetHandler)
	+~NetworkManager()

	+send(const std::string& message) : void
	+disconnect() : void
	+isConnected() : bool {query}

	+setDisconnectHandler(const std::function<void ( )> handler) : void
	+setServerInfo(const config::ServerInfo& serverInfo) : void
	+start(const config::ServerInfo& serverInfo) : void
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
