@startuml (id = GameStateView)

abstract class GameStateView {
	+GameStateView()
	+GameStateView(const GameStateView &)
	+GameStateView(GameStateView& &)
	+~GameStateView()
	+{abstract} getGameMode() : GameMode {query}
	+operator=(const GameStateView &) : GameStateView&
	+operator=(GameStateView& &) : GameStateView&
	+{abstract} getPlayerState(PlayerID playerID) : PlayerState* {query}
	+{abstract} getTetris(PlayerID playerID) : Tetris* {query}
	+{abstract} getWinner() : std::optional<PlayerID> {query}
	+{abstract} getPlayerToTetris() : std::vector<std::pair<PlayerState , Tetris>>& {query}
}


@enduml