@startuml (id=bonus)

class Bonus {

    + Bonus(BonusType)
    + ~Bonus()
    + {static} makeBonus(BonusType bonusType) : static BonusPtr
    + friend std::ostream &operator<<(std::ostream&, const Bonus&)
    + BonusType {
        SlowDown
        MiniTetrominoes
        NumBonusType
    }
    + static makeBonus(BonusType) : BonusPtr
    + getBonusType() : BonusType
    + friend std::ostream &operator<<(std::ostream&, const Bonus&)
    - friend BonusTest
    # Bonus

    - friend BonusTest
}

@enduml