/' authors Ernest Jonas Rafaou '/

@startuml (id=bonus)

class Bonus {

    + Bonus(BonusType)
    + ~Bonus()
    + {static} makeBonus(BonusType bonusType) : static BonusPtr
    + friend std::ostream &operator<<(std::ostream&, const Bonus&)
 
    + static makeBonus(BonusType) : BonusPtr
    + getBonusType() : BonusType
    + friend std::ostream &operator<<(std::ostream&, const Bonus&)
    - friend BonusTest
    # Bonus

}

@enduml