@startuml

skinparam style strictuml
actor Actor
participant LoginUI
participant LoginManager
participant AcountServer
participant MainUIManager
participant RegisterManager

activate Actor 
Actor -> LoginUI : loginRequest(username, password)
activate LoginUI
LoginUI ->LoginManager : tryLogin(username, password)
activate LoginManager 
LoginManager -> LoginManager : checkCredentialsValidity()
alt InvalidUsername
    LoginManager --> LoginUI : invalidUsername 
    LoginUI -> LoginUI : displayError()
else else
    LoginManager -> AcountServer : checkCredentials(username, password)
    activate AcountServer
    alt InvalidCredentials 
        AcountServer --> LoginManager : InvalidCredentials
        LoginManager --> LoginUI : InvalidCredentials
        LoginUI -> LoginUI : displayError()
        LoginManager -> RegisterManager : <<start>> RegisterManager\n(username, password)
        activate RegisterManager
        deactivate RegisterManager

    else
        AcountServer --> LoginManager : validCrendials
        deactivate AcountServer
        LoginManager --> LoginUI : <<destroy>>
        LoginManager -> MainUIManager : << create>>
        activate MainUIManager
        deactivate MainUIManager

    end   
end 

@enduml