@startuml ConnexionSequence

skinparam style strictuml
actor Actor
participant LoginUI
participant LoginManager
participant AcountServer
participant MainUIManager

'participant RegisterManager


'checkCredentialsValidity() : verify the validity of the characters in the username
'checkCredentials() : verify if the credentials exists in AcountServer
'InvalidCredentials : the creadentials do not exists in AcountServer or bad password for an existing account


activate Actor 
Actor -> LoginUI : loginRequest(username, password)
activate LoginUI
LoginUI ->LoginManager : tryLogin(username, password)
activate LoginManager 
                    
LoginManager -> LoginManager : checkCredentialsValidity()
alt invalidUsername
    LoginManager --> LoginUI : invalidUsername 
    LoginUI -> LoginUI : displayError()
else else 
    LoginManager -> AcountServer : checkCredentials(username, password)
    activate AcountServer
    alt InvalidCredentials 
        AcountServer --> LoginManager : InvalidCredentials
        LoginManager --> LoginUI : InvalidCredentials
        LoginUI -> LoginUI : displayError()
    else else 
        AcountServer --> LoginManager : validCredendials
        deactivate AcountServer
        LoginManager --> LoginUI : <<destroy>>
        LoginManager -> MainUIManager : << create>>
        activate MainUIManager
        deactivate MainUIManager

    end   
end

@enduml
