@startuml

skinparam style strictuml

actor Actor
activate Actor
participant MainUI
participant MatchmakingManager 
participant MatchmakingService 

Actor -> MainUI: requestMatchmaking()
activate MainUI

MainUI -> MainUI: displayLoadingScreen()
MainUI -> MatchmakingManager: processJoinRequest()
activate MatchmakingManager

MatchmakingManager -> MatchmakingService: submitJoinRequest(account)
activate MatchmakingService

MatchmakingService -->> MatchmakingManager: notifySessionCreated()
deactivate MatchmakingService
MatchmakingManager -->> MainUI: handleMatchmakingSuccess()
deactivate MatchmakingManager

@enduml
