@startuml ConnexionSequence

skinparam style strictuml
actor User
participant Controller
participant ClientLink
participant ClientManager
participant Network

activate Network
activate ClientManager
activate User
User -> Controller : run()
activate Controller
Controller -> Network : connect()
Network -> ClientLink : <<create>> 
activate ClientLink
ClientLink -> ClientManager : authPacketHandler(BindingType, data) 
ClientManager -> ClientManager : addClientInWaitingForAuth(ClientLink)

User -> Controller : tryLogin(username, password)
Controller -> ClientLink : send(data)
ClientLink -> ClientManager : authPacketHandler(BindingType, data)
ClientManager -> ClientManager : checkCredentials(data)
ClientManager -> ClientLink : handleMessage(checkCredentials(data))
ClientLink -> Controller : writeSocket(isIdentify)
Controller -> Controller : handlePacket(isIdentify)
alt isIdentify == false
    Controller -> Controller : authenticationState = Unauthenticated
else 
    Controller -> Controller : authenticationState = Authenticated
    ClientLink --> ClientManager : authSuccessCallBack
    ClientManager -> ClientManager : addConnection(ClientLink, username)
end 
@enduml
