@startuml InscriptionSequence

skinparam style strictuml
actor User
participant Controller
participant ClientLink
participant ClientManager
participant Network

activate Network
activate ClientManager
activate User
User -> Controller : run()
activate Controller
Controller -> Network : connect()
Network -> ClientLink : <<create>> 
activate ClientLink
ClientLink -> ClientManager : authPacketHandler(BindingType, data)
ClientManager -> ClientManager : addClientInWaitingForAuth(ClientLink)

User -> Controller : tryRegister(username, password)
Controller -> ClientLink : send(data)
ClientLink -> ClientManager : authPacketHandler(BindingType, data)
ClientManager -> ClientManager : attemptCreateAccount(data)
ClientManager -> ClientLink : handleMessage(attemptCreateAccount)
ClientLink -> Controller : writeSocket(attemptCreateAccount)
Controller -> Controller : handlePacket(attemptCreateAccount)
alt attemptCreateAccount == false
    Controller -> Controller : registrationState = Unregistered
else 
    Controller -> Controller : registrationState = Registered
end 
@enduml
