@startuml





/' Objects '/

namespace bindings {
	class BigDrop {
		+{static} from_json(const nlohmann::json& j) : BigDrop
		+to_json() : nlohmann::json {query}
	}

	class BuyBonus {
		+bonusType : BonusType
		+{static} from_json(const nlohmann::json& j) : BuyBonus
		+to_json() : nlohmann::json {query}
	}

	class BuyPenalty {
		+{static} from_json(const nlohmann::json& j) : BuyPenalty
		+penaltyType : PenaltyType
		+stashForLater : bool
		+to_json() : nlohmann::json {query}
	}

	class EmptyPenaltyStash {
		+{static} from_json(const nlohmann::json& j) : EmptyPenaltyStash
		+to_json() : nlohmann::json {query}
	}

	class HoldNextTetromino {
		+{static} from_json(const nlohmann::json& j) : HoldNextTetromino
		+to_json() : nlohmann::json {query}
	}

	class MoveActive {
		+{static} from_json(const nlohmann::json& j) : MoveActive
		+tetrominoMove : TetrominoMove
		+to_json() : nlohmann::json {query}
	}

	class QuitGame {
		+{static} from_json(const nlohmann::json& j) : QuitGame
		+to_json() : nlohmann::json {query}
	}

	class RotateActive {
		+{static} from_json(const nlohmann::json& j) : RotateActive
		+rotateClockwise : bool
		+to_json() : nlohmann::json {query}
	}

	class SelectTarget {
		+{static} from_json(const nlohmann::json& j) : SelectTarget
		+to_json() : nlohmann::json {query}
		+targetId : size_t
	}
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
