/' authors Ernest Jonas Rafaou '/
@startuml (id=Vec2)
class Vec2 {
	-x_ : int
	-y_ : int

	+Vec2(int x, int y)
	+Vec2(const Vec2 &)
	+Vec2(Vec2& &)
	+~Vec2()

	+decltype(auto ) get () {query}
	+getX() : int {query}
	+getY() : int {query}

	+moveX(int x) : void
	+moveY(int y) : void
	+setX(int x) : void
	+setY(int y) : void

	+operator+(const Vec2& other) : Vec2 {query}
	+operator-(const Vec2& other) : Vec2 {query}
	+operator-() : Vec2 {query}
	+operator+=(const Vec2& other) : Vec2&
	+operator-=(const Vec2& other) : Vec2&
	+operator=(const Vec2 &) : Vec2&
	+operator=(Vec2& &) : Vec2&
	+operator!=(const Vec2& other) : bool {query}
	+operator==(const Vec2& other) : bool {query}
	+operator<<(std::ostream& os, const Vec2& vec2) : std :: ostream&

	+rotateAround(const Vec2& rotationCenter, bool rotateClockwise) : Vec2&
	
	+serialize() : nlohmann::json {query}
	+deserialize(const nlohmann::json& j) : void
}
@enduml