@startuml InscriptionSequence

skinparam style strictuml

actor Actor
participant RegisterUI
participant RegisterManager
participant AccountServer
participant LoginManager
activate Actor
activate RegisterManager

Actor -> RegisterUI : registerRequest()
activate RegisterUI
RegisterUI -> RegisterManager : tryRegister(username, password)

RegisterManager -> RegisterManager : checkCredentialsValidity(username, password)
alt invalidCredentials
    RegisterManager -->> RegisterUI : invalidCredentials
    RegisterUI -> RegisterUI : displayError()
else else
    alt already_registered
        RegisterManager --> RegisterUI : <<destroy>>
        deactivate RegisterUI
        RegisterManager -> LoginManager : <<start>>  LoginManager(username, password)
        activate LoginManager
        
        deactivate LoginManager
         
    else else
        activate RegisterUI 
        RegisterManager -> AccountServer : CreateAccount(username, password)
       

        activate AccountServer
    alt Creation failed
        AccountServer -->> RegisterManager : creationFailed
        RegisterUI -> RegisterUI : displayError()
    else else 
        AccountServer -->> RegisterManager : creationSucceed
        RegisterManager -->> RegisterUI : <<destroy>>
        deactivate RegisterUI

RegisterManager -> LoginManager : <<start>> LoginManager()
activate LoginManager
deactivate RegisterManager
end
end
deactivate LoginManager
deactivate AccountServer 
end
 
@enduml
