@startuml Game

!include Tetrominoes.plantuml!0

' skinparam class { 
'     BackgroundColor AliceBlue
' }

class GameEngine{
    
}

class Player {
    -isPlaying_ : bool
    +isPlaying() : bool
    
}

 
@enduml
