@startuml Game

!include Board.plantuml!0

!include BoardUpdate.plantuml!0

!include Coordinate.plantuml!0

!include Event.plantuml!0

!include GridCell.plantuml!0

!include RotationState.plantuml!0

!include Tetris.plantuml!0

!include Tetrominoes.plantuml!0

' skinparam class { 
'     BackgroundColor AliceBlue
' }

' class GameEngine{
    
' }

' class Player {
'     -isPlaying_ : bool
'     +isPlaying() : bool
    
' }

' AbstractTetromino *-- Coordinate : uses
' AbstractTetromino - "1"RotationState

@enduml
