@startuml (id=Tetris)

class Tetris {
    - isAlive_ : bool
    - board_ : Board
    - activeTetromino_ : unique_ptr<Tetromino>
    - previewTetromino_ : unique_ptr<Tetromino>
    - eventQueue_ : queue<EventType> 
    - tetrominoesQueue_ : queue<unique_ptr>Tetromino>> 
    - queueMutex_ : pthread_mutex_t
    - isAliveMutex_ : pthread_mutex_t

    - placeActive() : void 
    - tryRotateActive( rotateClockwise : bool) : void
    - tryMoveActive( direction : Direction) : void 

    - bigDrop() : void
    - checkCanDrop() : const bool 
    - updatePreviewVertical() : void

    - setIsAlive( isAlive : bool ) : void

    - fillTetrominoesQueue() : void
    - fetchNewTetromino() : void

    - addEvent(event : EventType) : void 
    - getNewEvent() : EventType
    
    - checkEmptyCell( rowIdx : size_t, colIdx : size_t) : const bool


    + run() : void
    + getIsAlive() : bool 
    + addEvent(event : EventType) : void
}
@enduml