@startuml (id=TetrominoQueue)
class TetrominoQueue {
    - queue_ : std::deque<TetrominoPtr>
    - {static} MINIMUM_ENQUEUED_NUM : static constexpr size_t
   
    + TetrominoQueue()
    + TetrominoQueue(const TetrominoQueue &) = default
    + TetrominoQueue(TetrominoQueue &&) = default
    + operator=(const TetrominoQueue &) : TetrominoQueue& = default
    + operator=(TetrominoQueue &&) : TetrominoQueue& = default
    + ~TetrominoQueue() = default
    + size() : size_t const noexcept
    + front() : TetrominoPtr&
    + refill() : void
    + fetchNext() : TetrominoPtr
    + insertNextTetromino(pTetromino : TetrominoPtr&&) : void
    + serialize() : nlohmann::json const
}
@enduml