name: C++ Royal Blocks Build (with Make + Cache)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make git g++ libcppunit-dev libsqlite3-dev qtbase5-dev libboost-system-dev
    - name: Build with Make
      run: |
        make
        
